# Generated by Django 2.2.5 on 2019-11-26 15:13

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('conversation', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ChatMesssage',
            new_name='ChatMessage',
        ),
    ]
