# Generated by Django 2.2.5 on 2019-11-27 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0005_auto_20191127_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='noOfRooms',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
